#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_dash/version.py`)
DASH_ELECTRUM_VERSION=${VERSION_STRING[2]}
DASH_ELECTRUM_VERSION=${DASH_ELECTRUM_VERSION#\'}
DASH_ELECTRUM_VERSION=${DASH_ELECTRUM_VERSION%\'}
export DASH_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_dash/version.py`)
DASH_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
DASH_ELECTRUM_APK_VERSION=${DASH_ELECTRUM_APK_VERSION#\'}
DASH_ELECTRUM_APK_VERSION=${DASH_ELECTRUM_APK_VERSION%\'}
export DASH_ELECTRUM_APK_VERSION

TRAVIS_TAG=3.2.3.1
TRAVIS_OS_NAME=linux
TRAVIS_PYTHON_VERSION=3.5

exprot TRAVIS_TAG
export TRAVIS_OS_NAME
export TRAVIS_PYTHON_VERSION

